name: complianceiq
type: drupal
php_version: "8.3"
mariadb_version: "10.11"
webserver_type: nginx-fpm
docroot: web
database:
  type: mariadb
  version: "10.11"

web_environment:
  - SCOLTA_API_KEY=SCOLTA_API_KEY_PLACEHOLDER

hooks:
  post-start:
    - exec: composer install --no-interaction
    - exec: |
        if [ -f /var/www/html/db/dump.sql.gz ]; then
          zcat /var/www/html/db/dump.sql.gz | mysql -u root -proot db
          drush cache:rebuild
        fi
